[project]
name = "desktop-app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ipykernel>=7.3.0",
    "openai>=3.10.0",
    "python-dotenv>=1.2.3",
    "pywebview>=6.2.1",
]

[project.scripts]
desktop-app = "desktop_app:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
